### PR TITLE
docs: :truck: Moved this post from the design docs.

### PR DESCRIPTION
**Pull request by lwjohnst86**
Moved @signekb's work from the design docs to here. Doesn't need a thorough review.

### CODE REVIEW

**Review by signekb — APPROVED** [review]
👍 At some point, someone (including myself) might need to review this

**Review by K-Beicher — APPROVED** [review]
I'm happy to add a review later, but for now here is my approval of the move.

**Comment by lwjohnst86** [comment]
@signekb when I uploaded it, I also reviewed and edited it 🦾

**Comment by signekb** [comment]
Ah, great! Thanks 🦾

**Pull request merged**
